{% set name = "qtdeclarative" %}
{% set version = "6.9.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/{{ name }}-everywhere-src-{{ version }}.tar.xz
    sha256: ccb94665df0199d7ee387b965b29677c8b89cfb1782bb6f01239b1d1524cec97
    folder: {{ name }}

build:
  number: 0
  skip: True  # [osx and x86_64]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}
  ignore_run_exports:
    - qtshadertools

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config     # [unix]
    - bison          # [linux]
    - flex           # [linux]
    - gperf          # [linux]
    - jom            # [win]
    - msys2-bison    # [win]
    - msys2-flex     # [win]
    - msys2-gperf    # [win]
    - cmake
    - ninja
    - perl
  host:
    - qtbase-devel {{ version }}
    - qtsvg {{ version }}
    - qtshadertools {{ version }}
    # Vulkan support
    - libvulkan-headers {{ libvulkan }}  # [not osx]
    - libvulkan-loader {{ libvulkan }}   # [not osx]
  run_constrained:
    - qt-main >={{ version }},<7
    - qt >={{ version }},<7

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - qtbase-devel
  files:
    - run_qt_test.sh    # [unix]
    - run_qt_test.bat   # [win]
    - test/test_qtdeclarative.cpp
    - test/CMakeLists.txt
  commands:
    - ./run_qt_test.sh  # [unix]
    - run_qt_test.bat   # [win]
    {% for each_qt_lib in ["Qml", "Quick"] %}
    - test -d $PREFIX/include/qt6/Qt{{ each_qt_lib }}                           # [unix]
    - test -f $PREFIX/lib/libQt6{{ each_qt_lib }}${SHLIB_EXT}                   # [unix]
    - if not exist %PREFIX%\\Library\\include\\qt6\\Qt{{ each_qt_lib }} exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\Qt6{{ each_qt_lib }}.lib exit 1      # [win]
    - if not exist %PREFIX%\\Library\\bin\\Qt6{{ each_qt_lib }}.dll exit 1      # [win]
    {% endfor %}

about:
  home: https://www.qt.io/
  license: LGPL-3.0-only
  license_file: {{ name }}/LICENSES/LGPL-3.0-only.txt
  license_family: LGPL
  summary: Cross-platform application and UI framework ({{ name[2:] }} libraries).
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time ({{ name[2:] }} libraries).
  doc_url: https://doc.qt.io/
  dev_url: https://github.com/qt/{{ name }}
